# Part 1 — Inspect & Understand the Dataset

In [1]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [2]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [3]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")
df.sample(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
1766,101590,41,73777,250949.55,327,0,Hyderabad,SME,Branch,2021-07-21 00:00:00,Yes,High,6842.68,18,6.8
147,100679,26,71413,116171.18,465,1,Pune,Corporate,Branch,2023-06-13 00:00:00,No,High,40134.29,52,3.9
811,101777,61,214139,45532.62,449,0,Delhi,SME,Agent,2023-01-25 00:00:00,Yes,High,missing,96,3.4
533,101684,55,45074,58334.29,673,2,Pune,SME,Agent,2026-02-08 00:00:00,Yes,Medium,31006.44,136,2.7
1197,101702,57,198942,218258.77,770,10,Kolkata,Corporate,Agent,2022-05-29 00:00:00,Yes,Low,48554.15,26,7.4
1404,100761,34,105532,206933.65,758,6,Pune,SME,Online,2025-03-19 00:00:00,Yes,Low,32046.59,71,1.5
302,101056,46,178812,179931.39,467,11,Kolkata,SME,Agent,2025-08-25 00:00:00,No,High,27281,135,8.7
996,100172,68,103797,219245.41,608,11,Delhi,Premium,Agent,2025-10-30 00:00:00,Yes,Medium,NaN,122,9.0
1585,100626,41,164999,268812.24,518,5,Bangalore,Premium,Branch,2026-02-24 00:00:00,Yes,High,31351.25,87,2.6
27,100874,not_available,116878,missing,674,1,Kolkata,Corporate,Mobile,2023-04-30 00:00:00,NO,Medium,5694.49,75,NaN

In [4]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB

In [5]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

print(df.isnull().sum())
print(df.isna().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

# Part 2 — Detect & Fix Data Quality Problems

In [8]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df.duplicated().sum()

np.int64(40)

In [9]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df = df.drop_duplicates()

print(df.duplicated().sum())

0

In [10]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df.select_dtypes(include="number")
df.select_dtypes(include="object")

,Age,Annual_Income,Account_Balance,Credit_Score,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions
0,55,44033,111350.85,772,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135
1,32,215546,254378.37,374,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106
2,23,226403,159975.42,668,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146
3,66,87824,295741.6,315,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115
4,67,31570,242423.78,370,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94
...,...,...,...,...,...,...,...,...,...,...,...,...
2035,42,88530,153490.72,677,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119
2036,31,205738,270989.4,392,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134
2037,25,211994,160507.65,737,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87
2038,64,30105,32117.15,794,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107
2039,55,248332,274980.99,783,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119

In [11]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].median())

In [12]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Annual_Income"] = df["Annual_Income"].fillna(df["Annual_Income"].median())
df["Annual_Income"] = df["Annual_Income"].astype(float)

# Part 3 — Numerical Cleaning

In [13]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Account_Balance"] = pd.to_numeric(df["Account_Balance"], errors="coerce")
df["Account_Balance"] = df["Account_Balance"].fillna(df["Account_Balance"].mean())

In [14]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Credit_Score"] = pd.to_numeric(df["Credit_Score"], errors="coerce")
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].median())
df["Credit_Score"] = df["Credit_Score"].astype(int)

In [15]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"], errors="coerce")
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(df["Monthly_Spend"].median())

In [16]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Transactions"] = pd.to_numeric(df["Transactions"], errors="coerce")
df["Transactions"] = df["Transactions"].fillna(df["Transactions"].median())
df["Transactions"] = df["Transactions"].astype(int)

In [17]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"], errors="coerce")
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(df["Satisfaction_Score"].mean())
df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)

# Part 4 — Date Cleaning

In [18]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

print(df["Join_Date"].head(20))
print(df["Join_Date"].isnull().sum())

0     2022-08-15 00:00:00
1     2025-01-11 00:00:00
2     2024-08-01 00:00:00
3     2021-05-15 00:00:00
4     2026-02-03 00:00:00
5     2023-06-04 00:00:00
6     2024-01-16 00:00:00
7     2024-06-26 00:00:00
8     2025-03-12 00:00:00
9     2021-10-07 00:00:00
10    2023-03-02 00:00:00
11    2025-11-22 00:00:00
12    2021-06-25 00:00:00
13    2025-11-19 00:00:00
14    2025-08-26 00:00:00
15    2024-05-05 00:00:00
16    2022-01-07 00:00:00
17    2022-05-25 00:00:00
18    2022-10-07 00:00:00
19    2023-08-10 00:00:00
Name: Join_Date, dtype: object
102

In [19]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

In [20]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

print(df["Join_Date"].isnull().sum())

df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())

128

# Part 5 — Categorical Cleaning

In [21]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["City"] = df["City"].replace({
    "mumbai": "Mumbai",
    "delhi": "Delhi",
    "bangalore": "Bangalore",
    "chennai": "Chennai"
})

df["City"].value_counts()

City
Mumbai       314
Delhi        288
Hyderabad    278
Kolkata      262
Pune         256
Chennai      255
Bangalore    254
hyderabad     20
pune          18
kolkata       14
Name: count, dtype: int64

In [22]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

print(df["Segment"].value_counts(dropna=False))

df["Segment"] = df["Segment"].fillna(df["Segment"].mode()[0])

df["Segment"].value_counts()

Segment
Premium      523
Retail       481
Corporate    475
SME          456
NaN          105
Name: count, dtype: int64

Segment
Premium      628
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

In [23]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "1": "Yes",
    1: "Yes",
    "N": "No",
    "NO": "No",
    "no": "No",
    "0": "No",
    0: "No"
})

df["Active"].value_counts()

Active
Yes    1371
No      610
Name: count, dtype: int64

In [24]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

print(df["Risk_Level"].value_counts(dropna=False))
print(df["Risk_Level"].isnull().sum())

df["Risk_Level"].value_counts()

Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64
0

Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

# Part 6 — Column Transformation

In [25]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df = df.rename(columns={
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})

df.columns

Index(['Customer_ID', 'Age', 'AnnualIncome', 'AccountBalance', 'CreditScore',
       'Tenure', 'City', 'Segment', 'Channel', 'CustomerJoinDate', 'Active',
       'RiskLevel', 'MonthlySpend', 'Transactions', 'SatisfactionScore'],
      dtype='object')

In [26]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df = df.add_prefix("Customer_")

df.columns

Index(['Customer_Customer_ID', 'Customer_Age', 'Customer_Annual_Income',
       'Customer_Account_Balance', 'Customer_Credit_Score',
       'Customer_Tenure_Years', 'Customer_City', 'Customer_Segment',
       'Customer_Channel', 'Customer_Join_Date', 'Customer_Active',
       'Customer_Risk_Level', 'Customer_Monthly_Spend',
       'Customer_Transactions', 'Customer_Satisfaction_Score'],
      dtype='object')

In [27]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

clean_df = df.drop("Customer_ID", axis=1)

clean_df.head()

,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7

# Part 7 — Create New Columns

In [28]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")

df["Income_Lakhs"] = df["Annual_Income"] / 100000

df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,0.44033
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,2.15546
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,2.26403
3,101968,66,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,0.87824
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,0.31570
5,101334,68,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5,0.37087
6,100415,47,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8,0.67229
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7,NaN
8,100417,63,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1,1.53267
9,101472,42,NaN,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1,NaN

In [29]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"], errors="coerce")

df["MonthlyIncome"] = df["Annual_Income"] / 12
df["Income_After_Spending"] = df["MonthlyIncome"] - df["Monthly_Spend"]

df.head()

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,MonthlyIncome,Income_After_Spending
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,3669.416667,-19396.773333
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,17962.166667,NaN
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,18866.916667,-9669.423333
3,101968,66,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,7318.666667,-5551.043333
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,2630.833333,-31532.186667

In [30]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Account_Balance"] = pd.to_numeric(df["Account_Balance"], errors="coerce")

df["Balance_Income_Ratio"] = df["Account_Balance"] / df["Annual_Income"].replace(0, pd.NA)

df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Balance_Income_Ratio
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,2.528805
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,1.180158
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,0.706596
3,101968,66,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,3.367435
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,7.678929
5,101334,68,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5,4.855730
6,100415,47,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8,1.481947
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7,NaN
8,100417,63,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1,1.446547
9,101472,42,NaN,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1,NaN

In [31]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/customer_analytics - customer_analytics.csv")

df.head(10)
df.tail(10)
df.sample(10)
df.info()

print(df.isnull().sum())
print(df.duplicated().sum())

df = df.drop_duplicates()

# Numeric cleaning
for col in ["Age", "Annual_Income", "Account_Balance",
            "Credit_Score", "Monthly_Spend",
            "Transactions", "Satisfaction_Score"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Annual_Income"] = df["Annual_Income"].fillna(df["Annual_Income"].median())
df["Account_Balance"] = df["Account_Balance"].fillna(df["Account_Balance"].mean())
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].median())
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(df["Monthly_Spend"].median())
df["Transactions"] = df["Transactions"].fillna(df["Transactions"].median())
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(df["Satisfaction_Score"].mean())

# Date
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Join_Date"] = df["Join_Date"].fillna(df["Join_Date"].median())

# Categories
df["City"] = df["City"].str.title()
df["Segment"] = df["Segment"].fillna(df["Segment"].mode()[0])

df["Active"] = df["Active"].replace({
    "Y": "Yes", "YES": "Yes", "yes": "Yes", "1": "Yes", 1: "Yes",
    "N": "No", "NO": "No", "no": "No", "0": "No", 0: "No"
})

# Rename
df = df.rename(columns={
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})

# Drop ID
df = df.drop("Customer_ID", axis=1)

df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   object
 2   Annual_Income       1933 non-null   object
 3   Account_Balance     1912 non-null   object
 4   Credit_Score        2036 non-null   object
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   object
 7   Segment             1935 non-null   object
 8   Channel             2040 non-null   object
 9   Join_Date           1938 non-null   object
 10  Active              1981 non-null   object
 11  Risk_Level          2040 non-null   object
 12  Monthly_Spend       1931 non-null   object
 13  Transactions        2038 non-null   object
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), object(12)
memory usage: 239.2+ KB
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
40
<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2000 non-null   float64
 1   AnnualIncome       2000 non-null   float64
 2   AccountBalance     2000 non-null   float64
 3   CreditScore        2000 non-null   float64
 4   Tenure             2000 non-null   int64
 5   City               1920 non-null   object
 6   Segment            2000 non-null   object
 7   Channel            2000 non-null   object
 8   CustomerJoinDate   2000 non-null   datetime64[ns]
 9   Active             1942 non-null   object
 10  RiskLevel          2000 non-null   object
 11  MonthlySpend       2000 non-null   float64
 12  Transactions       2000 non-null   float64
 13  SatisfactionScore  2000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 234.4+ KB

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,CustomerJoinDate,MonthlySpend,Transactions,SatisfactionScore
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000.000000,2000.00000,2000.000000
mean,47.006000,138362.001000,151344.558019,576.251500,7.574000,2023-08-23 23:16:47.999999744,24846.208835,75.46050,5.605417
min,18.000000,25163.000000,55.960000,300.000000,0.000000,2021-01-01 00:00:00,559.580000,1.00000,1.000000
25%,34.000000,88617.000000,83956.797500,434.000000,4.000000,2022-06-10 12:00:00,13115.135000,40.00000,3.600000
50%,47.000000,139914.000000,151344.558019,570.500000,8.000000,2023-08-24 00:00:00,24625.170000,76.00000,5.605417
75%,61.000000,188465.000000,219656.717500,720.250000,12.000000,2024-11-05 00:00:00,36337.937500,112.00000,7.700000
max,75.000000,249977.000000,299914.140000,850.000000,15.000000,2026-03-13 00:00:00,49942.820000,149.00000,10.000000
std,16.184991,61981.578361,82600.275042,160.930148,4.610548,NaN,13850.626971,42.57714,2.527486

In [32]:
# Analytical features
df["Income_Lakhs"] = df["AnnualIncome"] / 100000
df["MonthlyIncome"] = df["AnnualIncome"] / 12
df["Income_After_Spending"] = df["MonthlyIncome"] - df["MonthlySpend"]
df["Balance_Income_Ratio"] = df["AccountBalance"] / df["AnnualIncome"].replace(0, pd.NA)

# Final validation
print("Duplicate rows:", df.duplicated().sum())
print("Missing values:")
print(df.isnull().sum())

print("\nFinal Data Types:")
df.info()

print("\nDescriptive Statistics:")
print(df.describe())

print("\nCity Distribution:")
print(df["City"].value_counts())

print("\nSegment Distribution:")
print(df["Segment"].value_counts())

print("\nActive Distribution:")
print(df["Active"].value_counts())

print("\nRisk Level Distribution:")
print(df["RiskLevel"].value_counts())

print("\nFirst 10 Rows:")
display(df.head(10))

print("\nLast 10 Rows:")
display(df.tail(10))

print("\nRandom 10 Rows:")
display(df.sample(10))

Duplicate rows: 0
Missing values:
Age                       0
AnnualIncome              0
AccountBalance            0
CreditScore               0
Tenure                    0
City                     80
Segment                   0
Channel                   0
CustomerJoinDate          0
Active                   58
RiskLevel                 0
MonthlySpend              0
Transactions              0
SatisfactionScore         0
Income_Lakhs              0
MonthlyIncome             0
Income_After_Spending     0
Balance_Income_Ratio      0
dtype: int64

Final Data Types:
<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    2000 non-null   float64
 1   AnnualIncome           2000 non-null   float64
 2   AccountBalance         2000 non-null   float64
 3   CreditScore            2000 non-null   float64
 4   Tenure                 2000 non-null   int64
 5   City                   1920 non-null   object
 6   Segment                2000 non-null   object
 7   Channel                2000 non-null   object
 8   CustomerJoinDate       2000 non-null   datetime64[ns]
 9   Active                 1942 non-null   object
 10  RiskLevel              2000 non-null   object
 11  MonthlySpend           2000 non-null   float64
 12  Transactions           2000 non-null   float64
 13  SatisfactionScore      2000 non-null   float64
 14  Income_Lakhs           2000 non-null   float64
 15  MonthlyIncome          2000 non-null   float64
 16  Income_After_Spending  2000 non-null   float64
 17  Balance_Income_Ratio   2000 non-null   float64
dtypes: datetime64[ns](1), float64(11), int64(1), object(5)
memory usage: 296.9+ KB

Descriptive Statistics:
               Age   AnnualIncome  AccountBalance  CreditScore       Tenure  \
count  2000.000000    2000.000000     2000.000000  2000.000000  2000.000000
mean     47.006000  138362.001000   151344.558019   576.251500     7.574000
min      18.000000   25163.000000       55.960000   300.000000     0.000000
25%      34.000000   88617.000000    83956.797500   434.000000     4.000000
50%      47.000000  139914.000000   151344.558019   570.500000     8.000000
75%      61.000000  188465.000000   219656.717500   720.250000    12.000000
max      75.000000  249977.000000   299914.140000   850.000000    15.000000
std      16.184991   61981.578361    82600.275042   160.930148     4.610548

                    CustomerJoinDate  MonthlySpend  Transactions  \
count                           2000   2000.000000    2000.00000
mean   2023-08-23 23:16:47.999999744  24846.208835      75.46050
min              2021-01-01 00:00:00    559.580000       1.00000
25%              2022-06-10 12:00:00  13115.135000      40.00000
50%              2023-08-24 00:00:00  24625.170000      76.00000
75%              2024-11-05 00:00:00  36337.937500     112.00000
max              2026-03-13 00:00:00  49942.820000     149.00000
std                              NaN  13850.626971      42.57714

       SatisfactionScore  Income_Lakhs  MonthlyIncome  Income_After_Spending  \
count        2000.000000   2000.000000    2000.000000            2000.000000
mean            5.605417      1.383620   11530.166750          -13316.042085
min             1.000000      0.251630    2096.916667          -46902.986667
25%             3.600000      0.886170    7384.750000          -24603.837500
50%             5.605417      1.399140   11659.500000          -12917.411667
75%             7.700000      1.884650   15705.416667           -1793.519167
max            10.000000      2.499770   20831.416667           19642.133333
std             2.527486      0.619816    5165.131530           14857.128756

       Balance_Income_Ratio
count           2000.000000
mean               1.495399
min                0.000281
25%                0.611383
50%                1.102992
75%                1.835454
max               11.427467
std                1.450448

City Distribution:
City
Mumbai       308
Hyderabad    292
Delhi        283
Kolkata      274
Pune         270
Bangalore    247
Chennai      246
Name: count, dtype: int64

Segment Distribution:
Segment
Premium      616
Retail       468
Corporate    468
SME          448
Name: count, dtype: int64

Active Distribution:
Active
Yes    1345
No      597
Name: count, dtype: int64

Risk Level Distribution:
RiskLevel
High      986
Low       540
Medium    474
Name: count, dtype: int64

First 10 Rows:

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
0,55.0,44033.0,111350.85,772.0,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135.0,3.1,0.44033,3669.416667,-19396.773333,2.528805
1,32.0,215546.0,254378.37,374.0,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106.0,8.2,2.15546,17962.166667,-6663.003333,1.180158
2,23.0,226403.0,159975.42,668.0,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146.0,6.3,2.26403,18866.916667,-9669.423333,0.706596
3,66.0,87824.0,295741.60,315.0,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115.0,9.7,0.87824,7318.666667,-5551.043333,3.367435
4,67.0,31570.0,242423.78,370.0,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94.0,3.7,0.31570,2630.833333,-31532.186667,7.678929
5,68.0,37087.0,180084.44,738.0,1,Chennai,Premium,Agent,2023-06-04,Yes,Low,15121.16,6.0,8.5,0.37087,3090.583333,-12030.576667,4.855730
6,47.0,67229.0,99629.81,464.0,4,Chennai,Retail,Online,2024-01-16,Yes,High,17655.61,31.0,2.8,0.67229,5602.416667,-12053.193333,1.481947
7,65.0,139914.0,61030.94,554.0,15,Kolkata,SME,Agent,2024-06-26,Yes,Medium,1720.85,139.0,9.7,1.39914,11659.500000,9938.650000,0.436203
8,63.0,153267.0,221707.97,508.0,5,Hyderabad,Premium,Mobile,2025-03-12,Yes,High,38043.07,76.0,7.1,1.53267,12772.250000,-25270.820000,1.446547
9,42.0,139914.0,41126.84,556.0,3,Kolkata,Corporate,Mobile,2021-10-07,Yes,Medium,11472.36,124.0,9.1,1.39914,11659.500000,187.140000,0.293944

Last 10 Rows:

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
2030,41.0,201611.0,40736.71,507.0,15,Bangalore,SME,Agent,2024-11-03,Yes,High,18815.18,58.0,7.2,2.01611,16800.916667,-2014.263333,0.202056
2031,61.0,128850.0,266135.80,840.0,9,Kolkata,SME,Mobile,2026-01-15,Yes,Low,34300.44,83.0,5.0,1.28850,10737.500000,-23562.940000,2.065470
2032,33.0,88037.0,129948.93,449.0,8,Mumbai,Premium,Mobile,2022-11-30,Yes,High,24625.17,147.0,9.7,0.88037,7336.416667,-17288.753333,1.476072
2033,43.0,122756.0,36633.45,487.0,8,Pune,Premium,Mobile,2021-07-04,No,High,10165.71,14.0,6.4,1.22756,10229.666667,63.956667,0.298425
2034,18.0,189232.0,235131.72,306.0,10,Hyderabad,SME,Mobile,2025-09-10,No,High,27227.44,85.0,5.9,1.89232,15769.333333,-11458.106667,1.242558
2035,42.0,88530.0,153490.72,677.0,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119.0,8.6,0.88530,7377.500000,-1077.920000,1.733771
2036,31.0,205738.0,270989.40,392.0,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134.0,2.6,2.05738,17144.833333,-16942.856667,1.317158
2037,25.0,211994.0,160507.65,737.0,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87.0,1.3,2.11994,17666.166667,-8852.573333,0.757133
2038,64.0,30105.0,32117.15,794.0,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107.0,9.3,0.30105,2508.750000,-18434.360000,1.066838
2039,55.0,248332.0,274980.99,783.0,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119.0,3.1,2.48332,20694.333333,-27816.986667,1.107312

Random 10 Rows:

,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore,Income_Lakhs,MonthlyIncome,Income_After_Spending,Balance_Income_Ratio
762,64.0,182584.0,151344.558019,703.0,0,Chennai,Corporate,Online,2022-10-28,Yes,Low,26128.16,114.0,4.7,1.82584,15215.333333,-10912.826667,0.828904
366,27.0,129648.0,198342.200000,378.0,14,Bangalore,Corporate,Branch,2022-04-24,Yes,High,7176.30,3.0,2.5,1.29648,10804.000000,3627.700000,1.529852
835,47.0,58243.0,217269.760000,373.0,12,Mumbai,Premium,Mobile,2023-06-24,Yes,High,48174.18,35.0,9.6,0.58243,4853.583333,-43320.596667,3.730401
1943,34.0,204785.0,203145.720000,372.0,10,Pune,Corporate,Online,2026-01-18,Yes,High,14970.31,93.0,7.7,2.04785,17065.416667,2095.106667,0.991995
1387,52.0,63787.0,245356.890000,568.0,12,Kolkata,Corporate,Online,2023-05-21,No,Medium,24625.17,49.0,6.0,0.63787,5315.583333,-19309.586667,3.846503
316,20.0,193280.0,67467.070000,701.0,15,Delhi,SME,Online,2021-03-27,Yes,Low,21634.83,70.0,6.5,1.93280,16106.666667,-5528.163333,0.349064
1906,69.0,221733.0,229073.720000,412.0,6,Pune,SME,Online,2022-02-21,Yes,High,30759.62,98.0,2.5,2.21733,18477.750000,-12281.870000,1.033106
791,66.0,111795.0,59291.770000,736.0,7,Chennai,Premium,Mobile,2024-05-08,Yes,Low,585.38,114.0,4.9,1.11795,9316.250000,8730.870000,0.530362
1336,27.0,68541.0,248794.270000,703.0,10,Hyderabad,Corporate,Mobile,2024-06-02,No,Low,6490.28,103.0,9.7,0.68541,5711.750000,-778.530000,3.629861
816,30.0,140395.0,151344.558019,392.0,14,Bangalore,Premium,Mobile,2023-08-24,Yes,High,24625.17,102.0,5.4,1.40395,11699.583333,-12925.586667,1.077991