# Allowed methods only:

In [ ]:
pd.DataFrame(), pd.read_csv(), head(), tail(), sample(), info(), isnull(), isna(), select_dtypes(),
describe(), drop(), duplicated(), drop_duplicates(), value_counts(), rename(), add_prefix(),
astype(), fillna(), mean(), median()

# EASY LEVEL:

In [3]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Bank_customer_churn.csv")

df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [4]:
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4695,4696,15786739,Clements,669,France,Male,37,1,125529.55,1,1,1,162260.93,0
7847,7848,15769915,Charlton,643,Spain,Female,20,0,133313.34,1,1,1,3965.69,0
3069,3070,15570932,Pirozzi,666,France,Male,43,7,137780.74,2,1,1,119100.05,1
5626,5627,15741417,Chibuzo,624,Spain,Female,35,7,119656.45,2,1,1,4595.05,0
7650,7651,15810716,Kerr,750,Germany,Male,42,8,151836.36,2,1,0,68695.38,0
7699,7700,15622289,Rizzo,605,Spain,Female,36,9,0.00,2,0,1,35521.63,0
9536,9537,15632051,Douglas,550,Germany,Female,42,10,128707.31,1,1,0,63092.65,1

In [6]:
df.info()

print("Total Columns:", len(df.columns))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
Total Columns: 14

In [7]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
df.select_dtypes(include="number")

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [9]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [10]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [11]:
clean_df = df.drop_duplicates()

clean_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [27]:
print(df["Exited"].value_counts())

KeyError: 'Exited'

# MEDIUM LEVEL:

In [14]:
df = df.rename(columns={
    "income":"Income",
    "credit_score":"Credit_Score",
    "avg_purchase_value":"Avg_Purchase_Value",
    "churn":"Churn"
})

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
df = df.add_prefix("Bank_")

df.head()

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [18]:
df["Bank_Age"] = df["Bank_Age"].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Bank_RowNumber        10000 non-null  int64
 1   Bank_CustomerId       10000 non-null  int64
 2   Bank_Surname          10000 non-null  object
 3   Bank_CreditScore      10000 non-null  int64
 4   Bank_Geography        10000 non-null  object
 5   Bank_Gender           10000 non-null  object
 6   Bank_Age              10000 non-null  float64
 7   Bank_Tenure           10000 non-null  int64
 8   Bank_Balance          10000 non-null  float64
 9   Bank_NumOfProducts    10000 non-null  int64
 10  Bank_HasCrCard        10000 non-null  int64
 11  Bank_IsActiveMember   10000 non-null  int64
 12  Bank_EstimatedSalary  10000 non-null  float64
 13  Bank_Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [19]:
df["churn"] = df["churn"].astype(str)

df.info()

KeyError: 'churn'

In [20]:
df["avg_purchase_value"] = df["avg_purchase_value"].fillna(
    df["avg_purchase_value"].mean()
)

df.head()

KeyError: 'avg_purchase_value'

In [21]:
df["age"] = df["age"].fillna(df["age"].median())

df.head()

KeyError: 'age'

In [22]:
new_df = df.rename(columns={
    "income":"Income",
    "credit_score":"Credit_Score",
    "avg_purchase_value":"Avg_Purchase_Value",
    "churn":"Churn"
})

new_df.head()

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [23]:
new_df = df.drop(columns=[
    "gender",
    "region",
    "transactions_month"
])

new_df.head(10)

KeyError: "['gender', 'region', 'transactions_month'] not found in axis"

In [24]:
new_df = df.drop(columns=["region"])

new_df.info()

KeyError: "['region'] not found in axis"

In [25]:
df = df.rename(columns={
    "num_products":"Products",
    "tenure_months":"Tenure"
})

df.head()

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

# HARD LEVEL:

In [28]:
df = df.rename(columns={
    "RowNumber": "Row_No",
    "CustomerId": "Customer_ID",
    "Surname": "Last_Name",
    "CreditScore": "Credit_Score",
    "Geography": "Country",
    "Gender": "Sex",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
})

df.head()

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [29]:
numeric_df = df.select_dtypes(include="number")

numeric_df.describe()

,Bank_RowNumber,Bank_CustomerId,Bank_CreditScore,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [30]:
print("Duplicate Rows:", df.duplicated().sum())

clean_df = df.drop_duplicates()

clean_df.info()

Duplicate Rows: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Bank_RowNumber        10000 non-null  int64
 1   Bank_CustomerId       10000 non-null  int64
 2   Bank_Surname          10000 non-null  object
 3   Bank_CreditScore      10000 non-null  int64
 4   Bank_Geography        10000 non-null  object
 5   Bank_Gender           10000 non-null  object
 6   Bank_Age              10000 non-null  float64
 7   Bank_Tenure           10000 non-null  int64
 8   Bank_Balance          10000 non-null  float64
 9   Bank_NumOfProducts    10000 non-null  int64
 10  Bank_HasCrCard        10000 non-null  int64
 11  Bank_IsActiveMember   10000 non-null  int64
 12  Bank_EstimatedSalary  10000 non-null  float64
 13  Bank_Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [31]:
customer_df = df.add_prefix("Customer_")

customer_df.head()

,Customer_Bank_RowNumber,Customer_Bank_CustomerId,Customer_Bank_Surname,Customer_Bank_CreditScore,Customer_Bank_Geography,Customer_Bank_Gender,Customer_Bank_Age,Customer_Bank_Tenure,Customer_Bank_Balance,Customer_Bank_NumOfProducts,Customer_Bank_HasCrCard,Customer_Bank_IsActiveMember,Customer_Bank_EstimatedSalary,Customer_Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [33]:
df["Customer_Bank_Age"] = df["Age"].astype(float)
df["Customer_Bank_Balance"] = df["Balance"].astype(float)
df["Customer_Bank_EstimatedSalary"] = df["Salary"].astype(float)

df.info()

KeyError: 'Age'

In [34]:
df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].median())

df.head()

KeyError: 'Credit_Score'

In [35]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df.head(8)

KeyError: 'Salary'

In [36]:
df = df.drop_duplicates()

df = df.rename(columns={
    "Exited": "Target"
})

df["Target"] = df["Target"].astype(str)

df.info()

KeyError: 'Target'

In [37]:
new_df = df.copy()

new_df = new_df.rename(columns={
    "Gender": "CustomerGender",
    "Geography": "Country"
})

new_df = new_df.add_prefix("Bank_")

new_df = new_df.drop(columns=["Bank_RowNumber"])

new_df.head(10)

KeyError: "['Bank_RowNumber'] not found in axis"

# MINI PROJECT:

In [38]:
import pandas as pd

# Load dataset
df = pd.read_csv("/Users/user/Downloads/Bank_customer_churn.csv")

# Dataset information
print(df.info())

# Missing values
print(df.isnull().sum())

# Remove duplicates
df = df.drop_duplicates()

# Rename columns
df = df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
})

# Convert datatypes
df["Age"] = df["Age"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

# Fill missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

# Remove columns
df = df.drop(columns=["RowNumber", "Surname"])

# First 10 rows
print(df.head(10))

# Statistical summary
print(df.describe())

# Target counts
print(df["Target"].value_counts())

# Final information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82
5     15574012           645     Spain    Male  44.0       8  113755.78
6     15592531           822    France    Male  50.0       7       0.00
7     15656148           376   Germany  Female  29.0       4  115046.74
8     15792365           501    France    Male  44.0       4  142051.07
9     15592389           684    France    Male  27.0       2  134603.88

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0              1          1               1  101348.88      1
1              1          0               1  112542.58      0
2              3          1               0  113931.57      1
3              2          0               0   93826.63      0
4              1          1               1   79084.10      0
5              2          1               0  149756.71      1
6              2          1               1   10062.80      0
7              4          1               0  119346.88      1
8              2          0               1   74940.50      0
9              1          1               1   71725.73      0
        Customer_ID  Credit_Score           Age        Tenure        Balance  \
count  1.000000e+04  10000.000000  10000.000000  10000.000000   10000.000000
mean   1.569094e+07    650.528800     38.921800      5.012800   76485.889288
std    7.193619e+04     96.653299     10.487806      2.892174   62397.405202
min    1.556570e+07    350.000000     18.000000      0.000000       0.000000
25%    1.562853e+07    584.000000     32.000000      3.000000       0.000000
50%    1.569074e+07    652.000000     37.000000      5.000000   97198.540000
75%    1.575323e+07    718.000000     44.000000      7.000000  127644.240000
max    1.581569e+07    850.000000     92.000000     10.000000  250898.090000

       NumOfProducts    HasCrCard  IsActiveMember         Salary
count   10000.000000  10000.00000    10000.000000   10000.000000
mean        1.530200      0.70550        0.515100  100090.239881
std         0.581654      0.45584        0.499797   57510.492818
min         1.000000      0.00000        0.000000      11.580000
25%         1.000000      0.00000        0.000000   51002.110000
50%         1.000000      1.00000        1.000000  100193.915000
75%         2.000000      1.00000        1.000000  149388.247500
max         4.000000      1.00000        1.000000  199992.480000
Target
0    7963
1    2037
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Credit_Score    10000 non-null  int64
 2   Geography       10000 non-null  object
 3   Gender          10000 non-null  object
 4   Age             10000 non-null  float64
 5   Tenure          10000 non-null  int64
 6   Balance         10000 non-null  float64
 7   NumOfProducts   10000 non-null  int64
 8   HasCrCard       10000 non-null  int64
 9   IsActiveMember  10000 non-null  int64
 10  Salary          10000 non-null  float64
 11  Target          10000 non-null  object
dtypes: float64(3), int64(6), object(3)
memory usage: 937.6+ KB
None

# BONUS CHALLENGE:

In [39]:
df["TotalMoney"] = df["Balance"] + df["EstimatedSalary"]

df.head()

KeyError: 'EstimatedSalary'

In [40]:
df["DoubleScore"] = df["CreditScore"] * 2

df.head()

KeyError: 'CreditScore'

In [41]:
df["AgeAfter10Years"] = df["Age"] + 10

df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,AgeAfter10Years
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,52.0
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,51.0
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,52.0
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,49.0
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,53.0

In [42]:
df["HasBalance"] = df["Balance"]

df["HasBalance"] = df["HasBalance"].fillna(
    df["HasBalance"].mean()
)

df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,AgeAfter10Years,HasBalance
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,52.0,0.00
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,51.0,83807.86
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,52.0,159660.80
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,49.0,0.00
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,53.0,125510.82

In [43]:
df["SalaryInLakhs"] = df["EstimatedSalary"] / 100000

df.head()

KeyError: 'EstimatedSalary'

In [44]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Churn_Modelling.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Downloads/Churn_Modelling.csv'