In [3]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

# Challenge 1 – Complete Data Cleaning

In [7]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

df["Age"] = df["Age"].fillna(df["Age"].median())

df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df = df.rename(columns={
    "Target": "CustomerStatus",
    "AnnualIncome": "Income"
})

df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

# Challenge 2 – Banking Report

In [8]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

numeric_df = df.select_dtypes(include="number")

print(numeric_df.describe())

df["Age"] = df["Age"].astype(float)

df["CreditScore"] = df["CreditScore"].astype(float)

df.info()

         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

# Challenge 3 – Duplicate Investigation

In [9]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

print("Duplicate rows:", df.duplicated().sum())

print("\nInformation BEFORE removing duplicates:")
df.info()

df = df.drop_duplicates()

print("\nInformation AFTER removing duplicates:")
df.info()

print("\nLast 20 rows:")
print(df.tail(20))

Duplicate rows: 20

Information BEFORE removing duplicates:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Information AFTER removing duplicates:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

Last 20 rows:
     CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
980       10981  41.0      199633.0      8498          847  173390.59       7
981       10982  34.0       98876.0      6414          541   59484.58       2
982       10983  69.0      188933.0     27126          334        NaN       1
983       10984  44.0      107221.0     47514          732  175352.25       1
984       10985  50.0       37397.0     23559          730  120423.19       8
985       10986  62.0       27169.0      3914          488  126031.27      10
986       10987  30.0      184704.0     20524          621  115161.87       1
987       10988  63.0      190178.0      9025          720  158528.46       5
988       10989  26.0       88335.0     11869          635  159905.73       3
989       10990  29.0      123152.0     25228          884   44897.43       0
990       10991  58.0       79954.0      6331          773   39653.24       2
991       10992  45.0           NaN     17549          452   17812.25       5
992       10993  18.0      157845.0     29018          764  165451.49       7
993       10994  31.0       69950.0     17945          594  149288.61       6
994       10995  56.0       76509.0     19044          493   83666.20       6
995       10996  34.0       81731.0     40980          761  181465.65       5
996       10997  47.0       42475.0      1176          780   26640.99       5
997       10998  31.0      120531.0     46929          733  147220.82       4
998       10999  21.0       33661.0     22314          540   94186.48       5
999       11000  63.0       31930.0       851          559  100908.40       6

    Geography  Gender    Segment Target
980    Canada    Male  Corporate   Stay
981    Canada   Other  Corporate   Stay
982    Canada  Female        SME  Churn
983       USA   Other  Corporate  Churn
984    France  Female  Corporate   Stay
985       USA    Male  Corporate  Churn
986       USA    Male        SME  Churn
987       NaN  Female        SME   Stay
988     India  Female  Corporate   Stay
989   Germany   Other        SME  Churn
990     India  Female        SME   Stay
991       USA   Other     Retail  Churn
992     India    Male        SME   Stay
993       USA  Female     Retail   Stay
994       USA    Male  Corporate  Churn
995   Germany   Other        SME   Stay
996    France  Female        SME   Stay
997     India    Male        SME   Stay
998       NaN   Other        SME   Stay
999        UK  Female        NaN   Stay

# Challenge 4 – HR Department

In [10]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.rename(columns={
    "CustomerID": "Employee_ID",
    "Age": "EmployeeAge",
    "Gender": "EmployeeGender",
    "AnnualIncome": "Salary",
    "Target": "PromotionStatus"
})

df = df.add_prefix("HR_")

df.sample(10)

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
180,10181,50.0,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
297,10298,46.0,118958.0,25118,382,136546.07,10,Germany,Male,SME,Churn
661,10662,46.0,100705.0,24471,722,51961.41,4,India,Male,SME,Stay
82,10083,63.0,50024.0,11232,618,21619.75,0,UK,Other,SME,Churn
614,10615,34.0,160536.0,28258,878,73128.82,4,France,Female,Retail,Stay
92,10093,63.0,148665.0,29871,317,18610.67,3,Canada,Other,Retail,Churn
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
130,10131,32.0,43692.0,28940,400,152073.94,1,Canada,Male,SME,Churn
581,10582,64.0,172199.0,32428,638,71427.67,10,France,Male,Retail,Stay
703,10704,27.0,44716.0,2973,771,71131.15,2,UK,Female,SME,Stay

# Challenge 5 – Finance Cleaning

In [11]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
)

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

# Challenge 6 – Data Type Audit

In [12]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)

df["AnnualIncome"] = df["AnnualIncome"].astype(float)

df["Balance"] = df["Balance"].astype(float)

df["Target"] = df["Target"].astype(str)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

# Challenge 7 – Customer Analytics

In [13]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.drop(columns=["Segment", "Geography"])

df = df.drop_duplicates()

print("First 10 rows:")
print(df.head(10))

print("\nDataset information:")
df.info()

print("\nStatistical summary:")
print(df.describe())

First 10 rows:
   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581        NaN       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5
5       10006  69.0       31390.0     48323          770  107245.62       6
6       10007  58.0      182141.0     24200          891   38457.72       1
7       10008  67.0       95861.0      5729          538  173296.73       6
8       10009  41.0       62638.0     24760          663   41901.41       4
9       10010  22.0      179680.0     42113          475  106827.98       3

   Gender Target
0    Male   Stay
1    Male  Churn
2    Male   Stay
3    Male  Churn
4   Other  Churn
5   Other   Stay
6   Other  Churn
7  Female   Stay
8   Other   Stay
9  Female  Churn

Dataset information:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(3), int64(4), object(2)
memory usage: 78.1+ KB

Statistical summary:
         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1000.000000  950.000000     950.000000   1000.000000  1000.000000
mean   10500.500000   44.212632  112458.303158  25285.558000   603.088000
std      288.819436   15.524244   52409.868404  14211.735656   176.605486
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10250.750000   30.000000   65922.500000  13213.000000   441.000000
50%    10500.500000   44.000000  112347.500000  24901.000000   606.500000
75%    10750.250000   58.000000  157973.000000  37960.250000   758.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     950.000000  1000.000000
mean    97557.565779     5.241000
std     55845.536430     3.179155
min       547.600000     0.000000
25%     50003.880000     2.000000
50%     95174.625000     5.000000
75%    144198.130000     8.000000
max    199885.880000    10.000000

# Challenge 8 – ML Dataset Preparation

In [14]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.drop_duplicates()

df = df.drop(columns=["CustomerID", "Segment"])

df["Age"] = df["Age"].fillna(df["Age"].median())

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
)

df["CreditScore"] = df["CreditScore"].fillna(
    df["CreditScore"].median()
)

df = df.rename(columns={
    "Target": "Output"
})

print(df.head())

df.info()

print(df.describe())

print(df["Output"].value_counts())

    Age  AnnualIncome  Spending  CreditScore        Balance  Tenure Geography  \
0  58.0       49184.0      2139          581   97557.565779       2    France
1  65.0      162964.0      6197          732    6356.540000       1       USA
2  56.0       26956.0     37281          503  143203.920000       8    Canada
3  55.0       92926.0       925          463  139627.880000       5       NaN
4  66.0      108236.0      7198          394   75985.460000       5        UK

  Gender Output
0   Male   Stay
1   Male  Churn
2   Male   Stay
3   Male  Churn
4  Other  Churn
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           1000 non-null   float64
 1   AnnualIncome  1000 non-null   float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       1000 non-null   float64
 5   Tenure        1000 non-null   int64
 6   Geography     950 non-null    object
 7   Gender        950 non-null    object
 8   Output        1000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 78.1+ KB
               Age   AnnualIncome      Spending  CreditScore        Balance  \
count  1000.000000    1000.000000   1000.000000  1000.000000    1000.000000
mean     44.202000  112452.763000  25285.558000   603.088000   97557.565779
std      15.130834   51081.480963  14211.735656   176.605486   54430.062006
min      18.000000   20227.000000    537.000000   300.000000     547.600000
25%      31.000000   68437.250000  13213.000000   441.000000   52074.240000
50%      44.000000  112347.500000  24901.000000   606.500000   97557.565779
75%      57.000000  155570.750000  37960.250000   758.250000  142297.910000
max      70.000000  199967.000000  49995.000000   900.000000  199885.880000

            Tenure
count  1000.000000
mean      5.241000
std       3.179155
min       0.000000
25%       2.000000
50%       5.000000
75%       8.000000
max      10.000000
Output
Churn    506
Stay     494
Name: count, dtype: int64

# Challenge 9 – Column Transformation

In [15]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df["NetWorth"] = df["Balance"] + df["AnnualIncome"]

df["AgeAfterRetirement"] = df["Age"] + 20

df["DoubleCreditScore"] = df["CreditScore"] * 2

df["IncomePerMonth"] = df["AnnualIncome"] / 12

df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

# Challenge 10 – Company Report

In [16]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

print("First five rows:")
print(df.head())

print("\nLast five rows:")
print(df.tail())

print("\nTen random rows:")
print(df.sample(10))

print("\nDataset information:")
df.info()

print("\nDescriptive statistics:")
print(df.describe())

df = df.rename(columns={
    "Target": "Customer_Status"
})

First five rows:
   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581        NaN       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target
0    France   Male        SME   Stay
1       USA   Male        SME  Churn
2    Canada   Male  Corporate   Stay
3       NaN   Male     Retail  Churn
4        UK  Other  Corporate  Churn

Last five rows:
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

Ten random rows:
     CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
309       10310  44.0      129185.0     37022          842   26818.55       3
453       10454  58.0           NaN      7322          808   28128.67       1
885       10886  21.0       36611.0     24932          653   90482.13       8
204       10205  37.0      142949.0     13215          676  135661.37       9
101       10102  27.0      167545.0     20412          387  198783.62       1
490       10491  40.0      140323.0     17014          523   93339.60      10
162       10163  47.0      152527.0     40177          740   19835.69       1
570       10571  39.0       29931.0      6235          375   10853.61       4
166       10167  69.0       54108.0     36962          361  117293.02       8
815       10816  37.0      167772.0     17568          362  125860.01       9

    Geography  Gender    Segment Target
309        UK    Male        NaN   Stay
453       USA  Female        NaN  Churn
885   Germany    Male  Corporate   Stay
204    Canada  Female  Corporate   Stay
101   Germany  Female        SME  Churn
490   Germany   Other  Corporate   Stay
162    France   Other        SME  Churn
570   Germany    Male        NaN  Churn
166   Germany  Female        SME  Churn
815       USA   Other     Retail  Churn

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Descriptive statistics:
         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000

# Challenge 11 – Missing Value Report

In [17]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

print("Total missing values:")
print(df.isnull().sum())

print("\nNumerical columns:")
print(df.select_dtypes(include="number").columns)

print("\nMean of Balance:")
print(df["Balance"].mean())

print("\nMedian of Age:")
print(df["Age"].median())

df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
)

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

print("\nInformation after filling missing values:")
df.info()

Total missing values:
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

Numerical columns:
Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure'],
      dtype='object')

Mean of Balance:
97523.53566563467

Median of Age:
44.0

Information after filling missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

# Challenge 12 – Customer Classification

In [18]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

print("Stay:")
print((df["Target"] == 0).sum())

print("\nChurn:")
print((df["Target"] == 1).sum())

df = df.rename(columns={
    "Target": "Customer_Class"
})

df["Customer_Class"] = df["Customer_Class"].astype(str)

print("\nCustomer Class counts:")
print(df["Customer_Class"].value_counts())

Stay:
0

Churn:
0

Customer Class counts:
Customer_Class
Churn    515
Stay     505
Name: count, dtype: int64

# Challenge 13 – Sales Department

In [19]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.rename(columns={
    "Balance": "AccountBalance",
    "AnnualIncome": "Salary",
    "CreditScore": "Score"
})

df = df.add_prefix("Sales_")

df.sample(20)

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
655,10656,24.0,45048.0,4680,784,109686.75,0,Canada,Other,Retail,Churn
791,10792,47.0,64774.0,18998,656,120888.05,2,Germany,Male,Corporate,Stay
61,10062,48.0,64483.0,43678,386,56757.28,10,France,Other,NaN,Churn
976,10977,24.0,65915.0,14531,581,87895.08,4,Germany,Male,Corporate,Stay
663,10664,37.0,22394.0,28709,599,119400.75,0,Germany,Female,Retail,Churn
731,10732,69.0,73034.0,9551,616,137706.42,8,USA,Female,Retail,Stay
130,10131,32.0,43692.0,28940,400,152073.94,1,Canada,Male,SME,Churn
219,10220,66.0,107167.0,9243,345,70459.81,5,France,Male,SME,Churn
234,10235,57.0,94862.0,45980,802,40035.67,2,India,Female,Retail,Stay
124,10125,30.0,82601.0,37973,692,46712.49,6,India,Female,SME,Stay
171,10172,29.0,91636.0,46552,616,184307.50,5,India,Male,Retail,Stay
114,10115,36.0,193692.0,26744,863,7339.43,1,UK,Female,Corporate,Churn
988,10989,26.0,88335.0,11869,635,159905.73,3,India,Female,Corporate,Stay
713,10714,53.0,181479.0,48712,836,49249.17,1,UK,Female,Corporate,Churn
268,10269,51.0,118782.0,21062,477,91932.71,8,UK,Other,Corporate,Churn
372,10373,53.0,152497.0,43299,806,81826.87,7,Canada,Other,Corporate,Stay
339,10340,66.0,90717.0,7199,435,17459.45,6,Canada,Other,SME,Churn
455,10456,22.0,111876.0,17320,410,144082.72,0,Canada,Female,SME,Churn
494,10495,43.0,193154.0,21444,443,144256.64,10,Canada,Female,NaN,Churn
488,10489,19.0,198834.0,1083,785,182303.09,10,USA,NaN,Retail,Stay

# Challenge 14 – Interview Challenge

In [20]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.drop_duplicates()

df = df.rename(columns={
    "Target": "CustomerStatus"
})

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
)

df["Balance"] = df["Balance"].astype(float)

df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

# Challenge 15 – Data Engineer Task

In [21]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

numeric_df = df.select_dtypes(include="number")

numeric_df = numeric_df.drop(
    columns=["CustomerID", "Target"]
)

numeric_df.describe()

KeyError: "['Target'] not found in axis"

# Challenge 16 – Mixed Cleaning

In [22]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.drop_duplicates()

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
)

df["Age"] = df["Age"].astype(int)

df["AnnualIncome"] = df["AnnualIncome"].astype(float)

df["Balance"] = df["Balance"].astype(float)

df = df.rename(columns={
    "Target": "CustomerStatus"
})

df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   int64
 2   AnnualIncome    1000 non-null   float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   int64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       950 non-null    object
 8   Gender          950 non-null    object
 9   Segment         950 non-null    object
 10  CustomerStatus  1000 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 93.8+ KB

# Challenge 17 – Real Company Dataset

In [23]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df = df.drop_duplicates()

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
)

df["CreditScore"] = df["CreditScore"].fillna(
    df["CreditScore"].median()
)

df = df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Annual_Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
})

df = df.add_prefix("Company_")

print("Summary:")
print(df.describe())

print("\nTarget counts:")
print(df["Company_Customer_Status"].value_counts())

Summary:
       Company_Customer_ID  Company_Age  Company_Annual_Income  \
count          1000.000000  1000.000000            1000.000000
mean          10500.500000    44.202000          112452.763000
std             288.819436    15.130834           51081.480963
min           10001.000000    18.000000           20227.000000
25%           10250.750000    31.000000           68437.250000
50%           10500.500000    44.000000          112347.500000
75%           10750.250000    57.000000          155570.750000
max           11000.000000    70.000000          199967.000000

       Company_Spending  Company_Credit_Score  Company_Balance  Company_Tenure
count       1000.000000           1000.000000      1000.000000     1000.000000
mean       25285.558000            603.088000     97557.565779        5.241000
std        14211.735656            176.605486     54430.062006        3.179155
min          537.000000            300.000000       547.600000        0.000000
25%        13213.000000            441.000000     52074.240000        2.000000
50%        24901.000000            606.500000     97557.565779        5.000000
75%        37960.250000            758.250000    142297.910000        8.000000
max        49995.000000            900.000000    199885.880000       10.000000

Target counts:
Company_Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

# Challenge 18 – Customer Summary

In [24]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

mean_balance = df["Balance"].mean()

median_balance = df["Balance"].median()

mean_age = df["Age"].mean()

median_income = df["AnnualIncome"].median()

print("Mean Balance:", mean_balance)

print("Median Balance:", median_balance)

print("Mean Age:", mean_age)

print("Median AnnualIncome:", median_income)

df["Balance"] = df["Balance"].fillna(mean_balance)

df["Age"] = df["Age"].fillna(mean_age)

df["AnnualIncome"] = df["AnnualIncome"].fillna(median_income)

Mean Balance: 97523.53566563467
Median Balance: 95100.06
Mean Age: 44.24948453608248
Median AnnualIncome: 112358.0

# Challenge 19 – Transformation Challenge

In [25]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000

df["Balance_in_Lakhs"] = df["Balance"] / 100000

df["SeniorCitizen"] = df["Age"] + 0

df["HighCreditScore"] = df["CreditScore"] * 1

df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,0.49184,NaN,58.0,581
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394

# Challenge 20 – Final Interview Project

In [26]:
import pandas as pd

df = pd.read_csv("/Users/user/Downloads/Task_dataset - Task_dataset.csv")

# Check information
df.info()

# Find missing values
print(df.isnull().sum())

# Remove duplicates
df = df.drop_duplicates()

# Rename columns
df = df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Annual_Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
})

# Convert Age
df["Age"] = df["Age"].fillna(
    df["Age"].median()
).astype(int)

# Convert AnnualIncome
df["Annual_Income"] = df["Annual_Income"].fillna(
    df["Annual_Income"].median()
).astype(float)

# Convert Balance
df["Balance"] = df["Balance"].fillna(
    df["Balance"].mean()
).astype(float)

# Remove Segment and CustomerID
df = df.drop(columns=["Segment", "Customer_ID"])

# Create new columns
df["TotalMoney"] = df["Balance"] + df["Annual_Income"]

df["AgeAfter5Years"] = df["Age"] + 5

df["MonthlyIncome"] = df["Annual_Income"] / 12

df["CreditScoreDouble"] = df["Credit_Score"] * 2

# Head
print("HEAD")
print(df.head())

# Tail
print("\nTAIL")
print(df.tail())

# Sample
print("\nSAMPLE")
print(df.sample(10))

# Describe
print("\nDESCRIBE")
print(df.describe())

# Target counts
print("\nTARGET COUNTS")
print(df["Customer_Status"].value_counts())

# Final information
print("\nFINAL INFORMATION")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
HEAD
   Age  Annual_Income  Spending  Credit_Score        Balance  Tenure  \
0   58        49184.0      2139           581   97557.565779       2
1   65       162964.0      6197           732    6356.540000       1
2   56        26956.0     37281           503  143203.920000       8
3   55        92926.0       925           463  139627.880000       5
4   66       108236.0      7198           394   75985.460000       5

  Geography Gender Customer_Status     TotalMoney  AgeAfter5Years  \
0    France   Male            Stay  146741.565779              63
1       USA   Male           Churn  169320.540000              70
2    Canada   Male            Stay  170159.920000              61
3       NaN   Male           Churn  232553.880000              60
4        UK  Other           Churn  184221.460000              71

   MonthlyIncome  CreditScoreDouble
0    4098.666667               1162
1   13580.333333               1464
2    2246.333333               1006
3    7743.833333                926
4    9019.666667                788

TAIL
     Age  Annual_Income  Spending  Credit_Score    Balance  Tenure Geography  \
995   34        81731.0     40980           761  181465.65       5   Germany
996   47        42475.0      1176           780   26640.99       5    France
997   31       120531.0     46929           733  147220.82       4     India
998   21        33661.0     22314           540   94186.48       5       NaN
999   63        31930.0       851           559  100908.40       6        UK

     Gender Customer_Status  TotalMoney  AgeAfter5Years  MonthlyIncome  \
995   Other            Stay   263196.65              39    6810.916667
996  Female            Stay    69115.99              52    3539.583333
997    Male            Stay   267751.82              36   10044.250000
998   Other            Stay   127847.48              26    2805.083333
999  Female            Stay   132838.40              68    2660.833333

     CreditScoreDouble
995               1522
996               1560
997               1466
998               1080
999               1118

SAMPLE
     Age  Annual_Income  Spending  Credit_Score        Balance  Tenure  \
944   21        37885.0     33145           327  194414.510000       6
24    32       174256.0     14932           307   14198.620000      10
991   45       112347.5     17549           452   17812.250000       5
775   31       157651.0     20312           479   22446.250000       0
227   45        63684.0     45704           754   70309.400000       0
847   47       197754.0     35664           452  148210.300000       3
473   43       164717.0     21873           582  103937.640000       0
243   23        85694.0     13364           864   54890.210000      10
510   32        78804.0     48155           434   97557.565779       0
994   56        76509.0     19044           493   83666.200000       6

    Geography  Gender Customer_Status     TotalMoney  AgeAfter5Years  \
944   Germany   Other           Churn  232299.510000              26
24      India     NaN           Churn  188454.620000              37
991       USA   Other           Churn  130159.750000              50
775       USA    Male           Churn  180097.250000              36
227    France  Female           Churn  133993.400000              50
847     India    Male           Churn  345964.300000              52
473    France   Other           Churn  268654.640000              48
243        UK   Other            Stay  140584.210000              28
510       NaN     NaN           Churn  176361.565779              37
994       USA    Male           Churn  160175.200000              61

     MonthlyIncome  CreditScoreDouble
944    3157.083333                654
24    14521.333333                614
991    9362.291667                904
775   13137.583333                958
227    5307.000000               1508
847   16479.500000                904
473   13726.416667               1164
243    7141.166667               1728
510    6567.000000                868
994    6375.750000                986

DESCRIBE
               Age  Annual_Income      Spending  Credit_Score        Balance  \
count  1000.000000    1000.000000   1000.000000   1000.000000    1000.000000
mean     44.202000  112452.763000  25285.558000    603.088000   97557.565779
std      15.130834   51081.480963  14211.735656    176.605486   54430.062006
min      18.000000   20227.000000    537.000000    300.000000     547.600000
25%      31.000000   68437.250000  13213.000000    441.000000   52074.240000
50%      44.000000  112347.500000  24901.000000    606.500000   97557.565779
75%      57.000000  155570.750000  37960.250000    758.250000  142297.910000
max      70.000000  199967.000000  49995.000000    900.000000  199885.880000

            Tenure     TotalMoney  AgeAfter5Years  MonthlyIncome  \
count  1000.000000    1000.000000     1000.000000    1000.000000
mean      5.241000  210010.328779       49.202000    9371.063583
std       3.179155   73150.769298       15.130834    4256.790080
min       0.000000   33432.390000       23.000000    1685.583333
25%       2.000000  156611.867500       36.000000    5703.104167
50%       5.000000  209916.897889       49.000000    9362.291667
75%       8.000000  263542.793945       62.000000   12964.229167
max      10.000000  390628.400000       75.000000   16663.916667

       CreditScoreDouble
count        1000.000000
mean         1206.176000
std           353.210972
min           600.000000
25%           882.000000
50%          1213.000000
75%          1516.500000
max          1800.000000

TARGET COUNTS
Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

FINAL INFORMATION
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Annual_Income      1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   Credit_Score       1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Geography          950 non-null    object
 7   Gender             950 non-null    object
 8   Customer_Status    1000 non-null   object
 9   TotalMoney         1000 non-null   float64
 10  AgeAfter5Years     1000 non-null   int64
 11  MonthlyIncome      1000 non-null   float64
 12  CreditScoreDouble  1000 non-null   int64
dtypes: float64(4), int64(6), object(3)
memory usage: 109.4+ KB